name: VCL Tests

on:
  pull_request:
    paths:
      - 'etc/varnish6.vcl'
      - 'tests/varnish/**'
      - '.github/workflows/vcl-tests.yml'

jobs:
  get-test-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: |
          FILES=$(ls tests/varnish/*.vtc | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=${FILES}" >> $GITHUB_OUTPUT

  test:
    needs: get-test-files
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_file: ${{ fromJson(needs.get-test-files.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker images
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('tests/varnish/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Run Varnish test
        working-directory: tests/varnish
        run: |
          test_file=$(basename ${{ matrix.test_file }})
          DOCKER_BUILDKIT=1 make test_single TEST=${test_file}
